version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn src.main:app --reload --workers 1 --host

networks:
  default:
    name: hello_fastapi
